import javax.swing.*;
/**
 *
 * @author Damien
 */
public class ClientInterface extends javax.swing.JFrame {

    ClientHelper helper;
    public String username;

    /**
     * Creates new form ClientInterface
     */
    public ClientInterface() {
        initComponents();
        loggedOut();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        tbxUsername = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        tbxDownloadPath = new javax.swing.JTextField();
        tbxFilename = new javax.swing.JTextField();
        lblLoginResponse = new javax.swing.JLabel();
        lblDownloadResponse = new javax.swing.JLabel();
        lblUploadResponse = new javax.swing.JLabel();
        lblLogoutResponse = new javax.swing.JLabel();
        lblFilename = new javax.swing.JLabel();
        lblDownloadLocation = new javax.swing.JLabel();
        fileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        tbxUsername.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(tbxUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 30));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, -1, -1));

        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        getContentPane().add(btnDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, -1, -1));
        getContentPane().add(tbxDownloadPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 320, -1));
        getContentPane().add(tbxFilename, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 220, -1));
        getContentPane().add(lblLoginResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 380, 30));
        getContentPane().add(lblDownloadResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, 470, 40));
        getContentPane().add(lblUploadResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 370, 40));
        getContentPane().add(lblLogoutResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 250, 30));

        lblFilename.setText("Filename");
        getContentPane().add(lblFilename, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, -1, -1));

        lblDownloadLocation.setText("Download Path");
        getContentPane().add(lblDownloadLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, -1, -1));

        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });
        getContentPane().add(fileChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        username = tbxUsername.getText();

        if (username.equals("")) {
            lblLoginResponse.setText("A username is required");
        } else {
            try {
                helper = new ClientHelper();
                String response = helper.login(username);

                String responseCode = response.substring(0, 3);

                if (responseCode.equals("200") || responseCode.equals("201")) {
                    loggedIn();
                } else {
                    lblLoginResponse.setText("");
                    lblLoginResponse.setText("Unable to Login: " + response);
                }

            } catch (Exception e) {
                System.out.print(e);
            }
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            helper = new ClientHelper();
            String response = helper.logout(username);
            if(response.substring(0,3).equals("200")){
                loggedOut();
                helper.done();
            }
            else{
                lblLogoutResponse.setText(response);
            }
            
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        
        lblDownloadResponse.setText("");
        lblUploadResponse.setText("");
        
        String path = fileChooser.getSelectedFile().getAbsolutePath();
        String fileName = fileChooser.getSelectedFile().getName();
        System.err.println("FILENAME: " + fileName + " PATH:: " + path);
        try {
            helper = new ClientHelper();
            String response = helper.upload(fileName, path);
            if (response.substring(0, 3).equals("200")) {
                lblUploadResponse.setText("File successfully uploaded");
            } else {
                lblUploadResponse.setText(response);
            }
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_fileChooserActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        
        lblDownloadResponse.setText("");
        lblUploadResponse.setText("");
                
        try {
            helper = new ClientHelper();
            String response = helper.download(tbxFilename.getText(), tbxDownloadPath.getText());

            if (response.substring(0, 3).equals("200")) {
                lblDownloadResponse.setText("File successfully downloaded");
            } else {
                lblDownloadResponse.setText(response);
            }
        } catch (Exception e) {
            System.out.print(e);
        }

    }//GEN-LAST:event_btnDownloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInterface().setVisible(true);
            }
        });
    }

    private void loggedIn() {
        fileChooser.setVisible(true);
        btnLogout.setVisible(true);
        btnDownload.setVisible(true);
        tbxDownloadPath.setVisible(true);
        tbxFilename.setVisible(true);
        btnLogin.setVisible(false);
        tbxUsername.setVisible(false);
        tbxUsername.setText("");
        lblLoginResponse.setText("");
        lblDownloadLocation.setVisible(true);
        lblFilename.setVisible(true);
    }

    private void loggedOut() {
        fileChooser.setVisible(false);
        btnLogout.setVisible(false);
        btnDownload.setVisible(false);
        tbxDownloadPath.setVisible(false);
        tbxDownloadPath.setText("");
        tbxFilename.setVisible(false);
        tbxFilename.setText("");
        btnLogin.setVisible(true);
        tbxUsername.setVisible(true);
        lblDownloadResponse.setText("");
        lblUploadResponse.setText("");
        lblDownloadLocation.setVisible(false);
        lblFilename.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel lblDownloadLocation;
    private javax.swing.JLabel lblDownloadResponse;
    private javax.swing.JLabel lblFilename;
    private javax.swing.JLabel lblLoginResponse;
    private javax.swing.JLabel lblLogoutResponse;
    private javax.swing.JLabel lblUploadResponse;
    private javax.swing.JTextField tbxDownloadPath;
    private javax.swing.JTextField tbxFilename;
    private javax.swing.JTextField tbxUsername;
    // End of variables declaration//GEN-END:variables
}
